export const t = {
  id: {
    nav: {
      links: ['Tentang', 'Layanan', 'Proyek', 'Pelanggan', 'Kontak'],
      cta: 'Hubungi Kami',
    },
    hero: {
      badge: 'HVAC | Automation Control | Panel Maker | Desain & Engineering',
      title1: 'PT. BARA',
      title2: 'SAKTI ZIWA',
      title3: 'ABADI',
      desc: 'Berkomitmen untuk selalu memberikan layanan terbaik di bidang HVAC, Automation Control, Panel Manufacturing, dan Design Engineering — mengutamakan kualitas baik dari sisi jasa maupun material.',
      btnServices: 'Layanan Kami',
      btnContact: 'Hubungi Kami',
    },
    stats: [
      { label: 'Referensi Proyek' },
      { label: 'Pelanggan Terpercaya' },
      { label: 'Layanan Utama' },
      { label: 'Komitmen Kualitas' },
    ],
    about: {
      tag: 'Tentang Kami',
      title: 'Tentang Kami',
      p1: 'adalah perusahaan yang bergerak di bidang HVAC, Automation Control, dan Panel Manufacturing. Kami berkomitmen untuk selalu memberikan pelayanan terbaik kepada pelanggan — baik dari sisi jasa maupun material.',
      p2: 'Kami mampu menangani berbagai pekerjaan mulai dari HVAC, kelistrikan, otomasi, hingga pembuatan panel. Kami juga menyediakan material dan layanan perbaikan yang berkaitan dengan bidang-bidang tersebut.',
      p3: 'Dengan pengalaman di berbagai industri — mulai dari transportasi, farmasi, manufaktur, hingga aerospace — kami memahami kebutuhan teknis yang kompleks dan siap menghadirkan solusi yang tepat dan andal.',
      imgAlt: 'Proyek MRT Jakarta',
      videoLabel: 'Company Profile',
      cards: [
        { icon: '🎯', title: 'Berpengalaman', desc: 'Telah menyelesaikan 24+ proyek di berbagai industri di seluruh Indonesia.' },
        { icon: '🤝', title: 'Terpercaya', desc: 'Dipercaya oleh 12+ perusahaan ternama seperti MRT Jakarta, Biofarma, dan GMF AeroAsia.' },
        { icon: '⚡', title: 'Responsif', desc: 'Tim kami siap merespons kebutuhan teknis Anda dengan cepat dan profesional.' },
        { icon: '🏆', title: 'Berkualitas', desc: 'Komitmen 100% terhadap kualitas — dari perencanaan hingga pelaksanaan di lapangan.' },
      ],
    },
    services: {
      tag: 'Apa yang Kami Lakukan',
      title: 'Layanan Kami',
      desc: 'Rangkaian lengkap layanan HVAC, otomasi, dan engineering untuk mendukung operasional industri Anda.',
      galleryLabel: 'Hasil Kerja Kami',
      items: [
        { icon: '❄️', title: 'Sistem HVAC', desc: 'Desain engineering, instalasi, perawatan, dan perbaikan sistem HVAC untuk fasilitas industri dan komersial.' },
        { icon: '⚙️', title: 'Automation Control', desc: 'Pemrograman PLC, pengembangan HMI, monitoring SCADA, dan integrasi BMS (Battery Management System).' },
        { icon: '🔲', title: 'Panel Maker', desc: 'Pembuatan panel listrik dan kontrol custom — panel distribusi, panel motor control, dan panel otomasi.' },
        { icon: '📐', title: 'Desain & Engineering', desc: 'Layanan desain engineering untuk sistem HVAC, sistem otomatis, dan sistem kelistrikan sesuai kebutuhan Anda.' },
        { icon: '🛠️', title: 'Instalasi & Maintenance', desc: 'Instalasi profesional, perawatan preventif, dan layanan perbaikan untuk HVAC, SCADA, BMS, dan panel kontrol.' },
        { icon: '💻', title: 'Custom Software', desc: 'Pengembangan software custom berbasis web dan desktop untuk monitoring industri, manajemen energi, dan otomasi.' },
      ],
      gallery: [
        { label: 'Panel Otomasi' },
        { label: 'Panel HMI' },
        { label: 'Panel Maker' },
        { label: 'Monitoring HVAC' },
        { label: 'Training Kit PLC' },
        { label: 'Maintenance Lapangan' },
      ],
    },
    projects: {
      tag: 'Track Record',
      title: 'Referensi Proyek',
      desc: 'Sebagian proyek yang telah berhasil kami selesaikan di berbagai wilayah Indonesia.',
    },
    customers: {
      tag: 'Yang Mempercayai Kami',
      title: 'Pelanggan Kami',
      desc: 'Dipercaya oleh perusahaan-perusahaan terkemuka di sektor transportasi, farmasi, manufaktur, dan aerospace.',
    },
    contact: {
      tag: 'Hubungi Kami',
      title: 'Kontak',
      desc: 'Hubungi kami untuk mendiskusikan kebutuhan HVAC, otomasi, atau panel Anda. Kami akan merespons dengan cepat.',
      labels: { phone: 'Telepon', whatsapp: 'WhatsApp', email: 'Email', address: 'Alamat', company: 'Perusahaan' },
      address: 'Jl. Permai 7 B II No. 26 RT/RW 04/14, Leuwigajah, Cimahi Selatan, Cimahi, Jawa Barat 40543',
      form: {
        name: 'Nama Lengkap', namePh: 'Budi Santoso',
        company: 'Perusahaan', companyPh: 'PT. Perusahaan Anda',
        email: 'Email', emailPh: 'budi@perusahaan.com',
        message: 'Pesan', messagePh: 'Ceritakan kebutuhan Anda...',
        submit: 'Kirim Pesan',
        sent: 'Pesan Terkirim!',
      },
    },
    footer: {
      tagline: 'HVAC | Automation Control | Panel Maker | Desain & Engineering',
      copy: `© ${new Date().getFullYear()} PT. Bara Sakti Ziwa Abadi. Semua hak dilindungi.`,
    },
  },

  en: {
    nav: {
      links: ['About', 'Services', 'Projects', 'Customers', 'Contact'],
      cta: 'Get in Touch',
    },
    hero: {
      badge: 'HVAC | Automation Control | Panel Maker | Design & Engineering',
      title1: 'PT. BARA',
      title2: 'SAKTI ZIWA',
      title3: 'ABADI',
      desc: 'Committed to consistently providing the best service in HVAC, Automation Control, Panel Manufacturing, and Design Engineering — delivering quality in both service and materials.',
      btnServices: 'Our Services',
      btnContact: 'Contact Us',
    },
    stats: [
      { label: 'Project References' },
      { label: 'Trusted Customers' },
      { label: 'Core Services' },
      { label: 'Committed to Quality' },
    ],
    about: {
      tag: 'Who We Are',
      title: 'About Us',
      p1: 'is a company operating in the HVAC, Automation Control, and Panel Manufacturing sectors. We are committed to consistently providing the best possible service to our customers — offering the best in both service and materials.',
      p2: 'We can handle a wide range of jobs including HVAC, electrical, automation, and panel manufacturing. We also provide materials and repair services related to our fields.',
      p3: 'With experience across various industries — from transportation, pharmaceuticals, manufacturing, to aerospace — we understand complex technical requirements and are ready to deliver precise and reliable solutions.',
      imgAlt: 'MRT Jakarta Project',
      videoLabel: 'Company Profile',
      cards: [
        { icon: '🎯', title: 'Experienced', desc: 'Completed 24+ projects across various industries throughout Indonesia.' },
        { icon: '🤝', title: 'Trusted', desc: 'Trusted by 12+ renowned companies such as MRT Jakarta, Biofarma, and GMF AeroAsia.' },
        { icon: '⚡', title: 'Responsive', desc: 'Our team is ready to respond to your technical needs quickly and professionally.' },
        { icon: '🏆', title: 'Quality-Driven', desc: '100% commitment to quality — from planning through execution in the field.' },
      ],
    },
    services: {
      tag: 'What We Do',
      title: 'Our Services',
      desc: 'A comprehensive range of HVAC, automation, and engineering services to support your industrial operations.',
      galleryLabel: 'Our Work in Action',
      items: [
        { icon: '❄️', title: 'HVAC System', desc: 'Design engineering, installation, maintenance, and repair of HVAC systems for industrial and commercial facilities.' },
        { icon: '⚙️', title: 'Automation Control', desc: 'PLC programming, HMI development, SCADA monitoring, and BMS (Battery Management System) integration.' },
        { icon: '🔲', title: 'Panel Maker', desc: 'Custom electrical and control panel manufacturing — distribution panels, motor control panels, and automation panels.' },
        { icon: '📐', title: 'Design & Engineering', desc: 'Engineering design for HVAC systems, automatic systems, and electrical systems tailored to your requirements.' },
        { icon: '🛠️', title: 'Installation & Maintenance', desc: 'Professional installation, preventive maintenance, and repair services for HVAC, SCADA, BMS, and control panels.' },
        { icon: '💻', title: 'Custom Software', desc: 'Web and desktop-based custom software development for industrial monitoring, energy management, and automation.' },
      ],
      gallery: [
        { label: 'Automation Panel' },
        { label: 'HMI Control Panel' },
        { label: 'Panel Maker' },
        { label: 'HVAC Monitoring' },
        { label: 'Training Kit PLC' },
        { label: 'Field Maintenance' },
      ],
    },
    projects: {
      tag: 'Track Record',
      title: 'Project References',
      desc: 'A selection of projects we have successfully delivered across Indonesia.',
    },
    customers: {
      tag: 'Who Trusts Us',
      title: 'Our Customers',
      desc: 'Trusted by leading companies across transportation, pharmaceutical, manufacturing, and aerospace sectors.',
    },
    contact: {
      tag: 'Get In Touch',
      title: 'Contact Us',
      desc: "Reach out to discuss your HVAC, automation, or panel requirements. We'll respond promptly.",
      labels: { phone: 'Phone', whatsapp: 'WhatsApp', email: 'Email', address: 'Address', company: 'Company' },
      address: 'Jl. Permai 7 B II No. 26 RT/RW 04/14, Leuwigajah, Cimahi Selatan, Cimahi, West Java 40543',
      form: {
        name: 'Full Name', namePh: 'John Smith',
        company: 'Company', companyPh: 'Your Company',
        email: 'Email', emailPh: 'john@company.com',
        message: 'Message', messagePh: 'Describe your needs...',
        submit: 'Send Message',
        sent: 'Message Sent!',
      },
    },
    footer: {
      tagline: 'HVAC | Automation Control | Panel Maker | Design & Engineering',
      copy: `© ${new Date().getFullYear()} PT. Bara Sakti Ziwa Abadi. All rights reserved.`,
    },
  },
}
